.TH "inc/IA.hh" 3 "Thu Jun 1 2017" "Version 1.0" "AI_DEV_KIT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/IA.hh
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'LuaManager\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIA\fP"
.br
.RI "represents the AI that is implemented in Ninja Gauntlet "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_CREATED\fP   ('AI created\&.')"
.br
.ti -1c
.RI "#define \fBAI_DESTROYED\fP   ('AI destroyed\&.')"
.br
.ti -1c
.RI "#define \fBAI_CALL_GETLIFE\fP   ('Call : getlife()')"
.br
.ti -1c
.RI "#define \fBAI_DEFAULT_NAME\fP   ('CPU1')"
.br
.ti -1c
.RI "#define \fBAI_DEFAULT_LIFE\fP   (100)"
.br
.in -1c
.SH "Detailed Description"
.PP 
!brief This is a mock of the final Ninja Gauntlet AI definition 
.PP
\fBAuthor:\fP
.RS 4
Charles Paulet 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_CALL_GETLIFE   ('Call : getlife()')"
Message that is printed when AI script call getLife 
.SS "#define AI_CREATED   ('AI created\&.')"
Message that is printed when AI object is created 
.SS "#define AI_DEFAULT_LIFE   (100)"
Default AI health points 
.SS "#define AI_DEFAULT_NAME   ('CPU1')"
Default AI name 
.SS "#define AI_DESTROYED   ('AI destroyed\&.')"
Message that is printed when AI object is destroyed 
.SH "Author"
.PP 
Generated automatically by Doxygen for AI_DEV_KIT from the source code\&.
