.TH "srcs/LuaManager.cpp" 3 "Thu Jun 1 2017" "Version 1.0" "AI_DEV_KIT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/LuaManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'IA\&.hh'\fP
.br
\fC#include 'LuaManager\&.hh'\fP
.br

.SH "Detailed Description"
.PP 
!brief This handle the member functions of the \fBLuaManager\fP class 
.PP
\fBAuthor:\fP
.RS 4
Charles Paulet 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AI_DEV_KIT from the source code\&.
