.TH "inc/LuaManager.hh" 3 "Thu Jun 1 2017" "Version 1.0" "AI_DEV_KIT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/LuaManager.hh
.SH SYNOPSIS
.br
.PP
\fC#include <lua5\&.2/lualib\&.h>\fP
.br
\fC#include <lua5\&.2/lauxlib\&.h>\fP
.br
\fC#include <lua5\&.2/lua\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuaManager\fP"
.br
.RI "represents the Lua scripts handler/loader "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERR_LUA_LOADSCRIPT\fP   ('Cannot load sript')"
.br
.in -1c
.SH "Detailed Description"
.PP 
!brief This define tools related to Lua scripts 
.PP
\fBAuthor:\fP
.RS 4
Charles Paulet 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define ERR_LUA_LOADSCRIPT   ('Cannot load sript')"
Error message triggered when lua script cannot be loaded 
.SH "Author"
.PP 
Generated automatically by Doxygen for AI_DEV_KIT from the source code\&.
