.TH "srcs/main.cpp" 3 "Thu Jun 1 2017" "Version 1.0" "AI_DEV_KIT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'LuaManager\&.hh'\fP
.br
\fC#include 'IA\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int const ac, char const *const *const av)"
.br
.RI "Entry point\&. "
.in -1c
.SH "Detailed Description"
.PP 
!brief This is the main where you can test various things 
.PP
\fBAuthor:\fP
.RS 4
Charles Paulet 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (int const ac, char const *const *const av)"

.PP
Entry point\&. 
.PP
\fBParameters:\fP
.RS 4
\fIac\fP Number of arguments given to the program 
.br
\fIav\fP The actual parameters given to the program 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AI_DEV_KIT from the source code\&.
